

print(' =========================== ')
print('|','                         ','|') 
print('|','Bem-vindo ao Insper Termo','|')
print('|','                         ','|')
print(' ==== Design de Software === ')
print('                         ')
print('Comandos: desisto')
print('                         ')
print(' Regras:')
print('                         ')
print('- Você tem 6 tentativas para acertar uma palavra aleatória de 5 letras.')
print('- A cada tentativa, a palavra testada terá suas letras coloridas conforme:')
print(' . Azul: a letra está na posição correta;')
print(' . Amarelo: a palavra tem a letra, mas está na posição errada;')
print(' . Cinza: a palavra não tem a letra.')
print('- Os acentos são ignorados;')
print('- As palavras podem possuir letras repetidas.')  
print('                         ')
print('Sorteando uma palavra...')
print('Já tenho uma palavra! Tente advinhá-la!')
print('                         ')
print('Você tem 6 tentativa(s)')
print('Qual o seu palpite?')